import reactPlugin from '@eslint-react/eslint-plugin'
import reactHooks from 'eslint-plugin-react-hooks'
import simpleImportSort from 'eslint-plugin-simple-import-sort'
import tseslint from 'typescript-eslint'

const sharedRules = {
  'simple-import-sort/imports': [
    'error',
    {
      groups: [
        ['^node:', '^@?\\w'], // node builtins + external packages
        ['^@/'], // internal aliases (@/*)
        ['^\\.'], // relative imports (./ and ../)
        ['^.*\\u0000$'], // type imports (all sources, last)
      ],
    },
  ],
  'simple-import-sort/exports': 'error',
  '@typescript-eslint/no-explicit-any': 'warn',
  '@typescript-eslint/no-unused-vars': ['error', { argsIgnorePattern: '^_' }],
  'no-unused-vars': 'off',
  '@typescript-eslint/no-namespace': 'off',
  '@typescript-eslint/consistent-type-imports': [
    'error',
    { prefer: 'type-imports', fixStyle: 'separate-type-imports' },
  ],
}

// Global ignores - applied to all configs
const globalIgnores = {
  ignores: [
    'dist/**',
    'dashboard/dist/**',
    'dashboard/@/src/dashboard-dist/**', // minified dist files
    'node_modules/**',
    'dashboard/node_modules/**',
    'dashboard/src/routeTree.gen.ts', // auto-generated by TanStack Router
  ],
}

export default tseslint.config(
  // ─── Global ignores ──────────────────────────────────────────────────────────
  globalIgnores,

  // ─── CLI (src/) ──────────────────────────────────────────────────────────────
  {
    files: ['src/**/*.ts'],
    languageOptions: {
      parser: tseslint.parser,
    },
    extends: [...tseslint.configs.recommended],
    plugins: { 'simple-import-sort': simpleImportSort },
    rules: sharedRules,
  },

  // ─── Dashboard (dashboard/src/) ───────────────────────────────────────────────
  {
    files: ['dashboard/src/**/*.{ts,tsx}'],
    extends: [...tseslint.configs.recommended, reactPlugin.configs['recommended-type-checked']],
    plugins: {
      'simple-import-sort': simpleImportSort,
      'react-hooks': reactHooks,
    },
    rules: {
      ...sharedRules,
      ...reactHooks.configs.recommended.rules,
      '@typescript-eslint/no-unused-vars': [
        'error',
        { argsIgnorePattern: '^_', varsIgnorePattern: '^_' },
      ],
    },
    languageOptions: {
      parserOptions: {
        project: './dashboard/tsconfig.json',
        tsconfigRootDir: import.meta.dirname,
      },
    },
  },

  // ─── Config files & other JS/TS ────────────────────────────────────────────────
  {
    files: ['**/*.{js,mjs,cjs,ts}'],
    ignores: ['src/**', 'dashboard/src/**'],
    languageOptions: {
      parser: tseslint.parser,
    },
    extends: [...tseslint.configs.recommended],
    plugins: { 'simple-import-sort': simpleImportSort },
    rules: sharedRules,
  }
)
