import { existsSync, mkdirSync, writeFileSync } from 'node:fs'
import { join, resolve } from 'node:path'

import { mergeCodexConfigToml } from './mcp-merge'
import { appendGitignore, slugify, writeAgentFile } from './scaffold-utils'
import {
  agentBuilderToml,
  agentConsultantToml,
  agentExplorerToml,
  agentLeadAsDefaultToml,
  agentLeadToml,
  agentReviewerToml,
  agentsMd,
  featureListJson,
  HEALTH_SH,
} from './templates'

import type { Materializer } from './index'
import type { HarnessConfig, Provider, ScaffoldOptions } from '@/types'

export class CodexCliMaterializer implements Materializer {
  async scaffold(config: HarnessConfig, opts: ScaffoldOptions): Promise<void> {
    const { cwd } = opts

    const write = (relPath: string, content: string, mode?: number) => {
      const abs = join(cwd, relPath)
      mkdirSync(resolve(abs, '..'), { recursive: true })
      writeFileSync(abs, content, { encoding: 'utf8', mode })
    }

    // AGENTS.md — always overwrite (generated from config)
    write('AGENTS.md', agentsMd(config))

    // health.sh — only create if it doesn't exist
    if (!existsSync(join(cwd, 'health.sh'))) {
      write('health.sh', HEALTH_SH, 0o755)
    }

    const tasks = opts.firstTask
      ? [{ slug: slugify(opts.firstTask.title), ...opts.firstTask }]
      : []
    write(join(config.storage.dir, 'feature_list.json'), featureListJson(tasks))

    if (!existsSync(join(cwd, config.storage.markdownFallback.path))) {
      write(
        config.storage.markdownFallback.path,
        `<!-- AUTO-GENERATED by agent-harness-kit — DO NOT EDIT MANUALLY -->\n<!-- Run ahk status to refresh -->\n\n# Current Session\n\nNo tasks in progress.\n`
      )
    }

    // .codex/agents/ — skip files the dev may have customized
    const projectName = config.project.name
    const allowedPaths = (config.agents.explorer.allowedPaths ?? []).join(', ')
    const writablePaths = (config.agents.builder.writablePaths ?? []).join(', ')

    writeAgentFile(cwd, '.codex/agents/lead.toml', agentLeadToml({ projectName }))
    writeAgentFile(cwd, '.codex/agents/explorer.toml', agentExplorerToml({ projectName, allowedPaths }))
    writeAgentFile(cwd, '.codex/agents/consultant.toml', agentConsultantToml({ projectName }))
    writeAgentFile(cwd, '.codex/agents/builder.toml', agentBuilderToml({ projectName, writablePaths }))
    writeAgentFile(cwd, '.codex/agents/reviewer.toml', agentReviewerToml({ projectName }))
    // Override Codex's built-in `default` agent so `lead` runs when no agent is selected
    writeAgentFile(cwd, '.codex/agents/default.toml', agentLeadAsDefaultToml({ projectName }))

    // .codex/config.toml — MERGE, never overwrite whole file
    mergeCodexConfigToml(join(cwd, '.codex/config.toml'), config.tools.mcp.port)

    appendGitignore(cwd)
  }

  async build(config: HarnessConfig, cwd: string): Promise<void> {
    const write = (relPath: string, content: string) => {
      const abs = join(cwd, relPath)
      mkdirSync(resolve(abs, '..'), { recursive: true })
      writeFileSync(abs, content, 'utf8')
    }

    write('AGENTS.md', agentsMd(config))

    const projectName = config.project.name
    const allowedPaths = (config.agents.explorer.allowedPaths ?? []).join(', ')
    const writablePaths = (config.agents.builder.writablePaths ?? []).join(', ')

    writeAgentFile(cwd, '.codex/agents/lead.toml', agentLeadToml({ projectName }))
    writeAgentFile(cwd, '.codex/agents/explorer.toml', agentExplorerToml({ projectName, allowedPaths }))
    writeAgentFile(cwd, '.codex/agents/consultant.toml', agentConsultantToml({ projectName }))
    writeAgentFile(cwd, '.codex/agents/builder.toml', agentBuilderToml({ projectName, writablePaths }))
    writeAgentFile(cwd, '.codex/agents/reviewer.toml', agentReviewerToml({ projectName }))
    writeAgentFile(cwd, '.codex/agents/default.toml', agentLeadAsDefaultToml({ projectName }))

    mergeCodexConfigToml(join(cwd, '.codex/config.toml'), config.tools.mcp.port)
  }

  async migrate(config: HarnessConfig, _to: Provider, _cwd: string): Promise<void> {
    void config
  }

  async syncPermissions(_cwd: string): Promise<void> {
    console.log('  Permissions sync not needed for codex-cli — skipping')
  }
}
