import { existsSync, mkdirSync, writeFileSync } from 'node:fs'
import { join, resolve } from 'node:path'
import type { HarnessConfig, Provider, ScaffoldOptions } from '../../types.js'
import type { Materializer } from './index.js'
import { HEALTH_SH, agentsMd, featureListJson, agentLead, agentExplorer, agentBuilder, agentReviewer } from './templates.js'
import { mergeOpencodeJson } from './mcp-merge.js'
import { writeAgentFile, appendGitignore, slugify } from './scaffold-utils.js'

export class OpenCodeMaterializer implements Materializer {
  async scaffold(config: HarnessConfig, opts: ScaffoldOptions): Promise<void> {
    const { cwd } = opts

    const write = (relPath: string, content: string, mode?: number) => {
      const abs = join(cwd, relPath)
      mkdirSync(resolve(abs, '..'), { recursive: true })
      writeFileSync(abs, content, { encoding: 'utf8', mode })
    }

    // AGENTS.md — always overwrite (generated from config)
    write('AGENTS.md', agentsMd(config))

    // health.sh — only create if it doesn't exist
    if (!existsSync(join(cwd, 'health.sh'))) {
      write('health.sh', HEALTH_SH, 0o755)
    }

    const tasks = opts.firstTask
      ? [{ slug: slugify(opts.firstTask.title), ...opts.firstTask }]
      : []
    write(join(config.storage.dir, 'feature_list.json'), featureListJson(tasks))

    if (!existsSync(join(cwd, config.storage.markdownFallback.path))) {
      write(
        config.storage.markdownFallback.path,
        `<!-- AUTO-GENERATED by agent-harness-kit — DO NOT EDIT MANUALLY -->\n<!-- Run ahk status to refresh -->\n\n# Current Session\n\nNo tasks in progress.\n`
      )
    }

    // .opencode/agents/ — skip files the dev may have customized
    const projectName = config.project.name
    const allowedPaths = (config.agents.explorer.allowedPaths ?? []).join(', ')
    const writablePaths = (config.agents.builder.writablePaths ?? []).join(', ')
    writeAgentFile(cwd, '.opencode/agents/lead.md', agentLead({ projectName }))
    writeAgentFile(cwd, '.opencode/agents/explorer.md', agentExplorer({ projectName, allowedPaths }))
    writeAgentFile(cwd, '.opencode/agents/builder.md', agentBuilder({ projectName, writablePaths }))
    writeAgentFile(cwd, '.opencode/agents/reviewer.md', agentReviewer({ projectName }))

    // opencode.json — MERGE, never overwrite whole file
    mergeOpencodeJson(join(cwd, 'opencode.json'), config.tools.mcp.port)

    appendGitignore(cwd)
  }

  async build(config: HarnessConfig, cwd: string): Promise<void> {
    const write = (relPath: string, content: string) => {
      const abs = join(cwd, relPath)
      mkdirSync(resolve(abs, '..'), { recursive: true })
      writeFileSync(abs, content, 'utf8')
    }

    write('AGENTS.md', agentsMd(config))

    const projectName = config.project.name
    const allowedPaths = (config.agents.explorer.allowedPaths ?? []).join(', ')
    const writablePaths = (config.agents.builder.writablePaths ?? []).join(', ')
    writeAgentFile(cwd, '.opencode/agents/lead.md', agentLead({ projectName }))
    writeAgentFile(cwd, '.opencode/agents/explorer.md', agentExplorer({ projectName, allowedPaths }))
    writeAgentFile(cwd, '.opencode/agents/builder.md', agentBuilder({ projectName, writablePaths }))
    writeAgentFile(cwd, '.opencode/agents/reviewer.md', agentReviewer({ projectName }))

    mergeOpencodeJson(join(cwd, 'opencode.json'), config.tools.mcp.port)
  }

  async migrate(config: HarnessConfig, _to: Provider, _cwd: string): Promise<void> {
    void config
  }
}

