import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs'
import { join, resolve } from 'node:path'
import type { HarnessConfig, Provider, ScaffoldOptions } from '../../types.js'
import type { Materializer } from './index.js'
import {
  HEALTH_SH,
  GITIGNORE_ENTRIES,
  agentsMd,
  mergeOpencodeJson,
  featureListJson,
  AGENT_LEAD,
  AGENT_EXPLORER,
  AGENT_BUILDER,
  AGENT_REVIEWER,
} from './templates.js'

export class OpenCodeMaterializer implements Materializer {
  async scaffold(config: HarnessConfig, opts: ScaffoldOptions): Promise<void> {
    const { cwd } = opts

    const write = (relPath: string, content: string, mode?: number) => {
      const abs = join(cwd, relPath)
      mkdirSync(resolve(abs, '..'), { recursive: true })
      writeFileSync(abs, content, { encoding: 'utf8', mode })
    }

    // AGENTS.md — always overwrite (generated from config)
    write('AGENTS.md', agentsMd(config))

    // health.sh — only create if it doesn't exist
    if (!existsSync(join(cwd, 'health.sh'))) {
      write('health.sh', HEALTH_SH, 0o755)
    }

    const tasks = opts.firstTask
      ? [{ slug: slugify(opts.firstTask.title), ...opts.firstTask }]
      : []
    write(join(config.storage.dir, 'feature_list.json'), featureListJson(tasks))

    if (!existsSync(join(cwd, config.storage.markdownFallback.path))) {
      write(
        config.storage.markdownFallback.path,
        `<!-- AUTO-GENERATED by agent-harness-kit — DO NOT EDIT MANUALLY -->\n<!-- Run ahk status to refresh -->\n\n# Current Session\n\nNo tasks in progress.\n`
      )
    }

    // .opencode/agents/ — skip files the dev may have customized
    writeAgentFile(cwd, '.opencode/agents/lead.md', AGENT_LEAD)
    writeAgentFile(cwd, '.opencode/agents/explorer.md', AGENT_EXPLORER)
    writeAgentFile(cwd, '.opencode/agents/builder.md', AGENT_BUILDER)
    writeAgentFile(cwd, '.opencode/agents/reviewer.md', AGENT_REVIEWER)

    // opencode.json — MERGE, never overwrite whole file
    mergeOpencodeJson(join(cwd, 'opencode.json'), config.tools.mcp.port)

    appendGitignore(cwd)
  }

  async build(config: HarnessConfig, cwd: string): Promise<void> {
    const write = (relPath: string, content: string) => {
      const abs = join(cwd, relPath)
      mkdirSync(resolve(abs, '..'), { recursive: true })
      writeFileSync(abs, content, 'utf8')
    }

    write('AGENTS.md', agentsMd(config))

    writeAgentFile(cwd, '.opencode/agents/lead.md', AGENT_LEAD)
    writeAgentFile(cwd, '.opencode/agents/explorer.md', AGENT_EXPLORER)
    writeAgentFile(cwd, '.opencode/agents/builder.md', AGENT_BUILDER)
    writeAgentFile(cwd, '.opencode/agents/reviewer.md', AGENT_REVIEWER)

    mergeOpencodeJson(join(cwd, 'opencode.json'), config.tools.mcp.port)
  }

  async migrate(config: HarnessConfig, _to: Provider, _cwd: string): Promise<void> {
    void config
  }
}

// ─── Shared helpers ───────────────────────────────────────────────────────────

function writeAgentFile(cwd: string, relPath: string, content: string): void {
  const abs = join(cwd, relPath)
  if (existsSync(abs)) return  // preserve dev customizations
  mkdirSync(resolve(abs, '..'), { recursive: true })
  writeFileSync(abs, content, 'utf8')
}

function appendGitignore(cwd: string): void {
  const giPath = join(cwd, '.gitignore')
  const existing = existsSync(giPath) ? readFileSync(giPath, 'utf8') : ''

  const toAdd = GITIGNORE_ENTRIES.split('\n')
    .filter((line) => line && !existing.includes(line))
    .join('\n')

  if (toAdd.trim()) {
    writeFileSync(giPath, existing + (existing.endsWith('\n') ? '' : '\n') + toAdd + '\n', 'utf8')
  }
}

function slugify(title: string): string {
  return title
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '')
    .slice(0, 64)
}
